spring:
  shardingsphere:
    datasource:
      names: ds-master,ds-slave-0,ds-slave-1
      ds-master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3307/sharding-jdbc-ms?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: 123456
      ds-slave-0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3308/sharding-jdbc-ms?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: 123456
      ds-slave-1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3308/sharding-jdbc-ms?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: 123456
    sharding:
      tables:
        coupon:
          actual-data-nodes: ds0.coupon_${0..1}
          table-strategy:
            inline:
              sharding-column: id
              algorithm-expression: coupon_$->{id%2}
          key-generator:
            column: id
            type: SNOWFLAKE
      binding-tables: coupon
      master-slave-rules:
        ds0:
          master-data-source-name: ds-master
          slave-data-source-names: ds-slave-0, ds-slave-1
    props:
      sql:
        show: true # 显示SQL

